---

- hosts: all
  become: true

  vars:
    csle_git_repo_url: "https://github.com/Limmen/csle"
    postgresql_url: "https://install.citusdata.com/community/deb.sh"
    user: "shahab"
    postgres_version: "15"

  tasks:
    
    - name: Check if PostgreSQL is installed, if you see error here just ignore it!
      shell: "psql --version"
      register: postgresql_installed
      ignore_errors: true

    - name: Download PostgreSQL
      ansible.builtin.get_url:
        url: "{{ postgresql_url }}"
        dest: /home/shahab
        mode: '0770'
      when: postgresql_installed.rc != 0

    - name: Install PostgreSQL
      shell: "/home/{{ user }}/deb.sh"
      when: postgresql_installed.rc != 0

    - name: Install PostgreSQL Citus extension
      apt:
        name: postgresql-15-citus-11.2
        state: present
        update_cache: yes
      when: postgresql_installed.rc != 0

    - name: Install libpq-dev lib
      apt:
        name: libpq-dev
        state: present
        update_cache: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install PostgreSQL python lib
      pip:
        name: psycopg2
        state: present

    - name: Set shared_preload_libraries using pg_conftool
      shell: "pg_conftool 15 main set shared_preload_libraries citus"

    - name: Set listen address using pg_conftool
      shell: "pg_conftool 15 main set listen_addresses '*'"

    - name: Run psql and set password for postgres user
      expect:
        command: sudo -u postgres psql -c "\password postgres"
        responses:
          Enter\ new\ password\ for\ user\ "postgres": "postgres"
          Enter\ it\ again: "postgres"  # Re-enter the password
    - name: Replace first line in postgres config file
      lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        regexp: '^local\s+all\s+all\s+peer$'
        line: "local\tall\t\tall\t\t\t\t\tmd5"
        state: present

    - name: Replace second line in postgres config file
      lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+scram-sha-256$'
        line: "host\tall\t\tall\t\t127.0.0.1/32\t\ttrust"
        state: present

    - name: Replace second line in postgres config file
      lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        regexp: '^host\s+all\s+all\s+::1/128\s+scram-sha-256$'
        line: "host\tall\t\tall\t\t::1/128\t\t\ttrust"
        state: present
    - name: Add the line for our network to the file
      lineinfile:
        path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        line: "host\tall\t\tall\t\t172.31.212.0/24\t\ttrust"
        insertafter: EOF
        state: present
