---

- hosts: all
  become: true

  vars:
    csle_git_repo_url: "https://github.com/Limmen/csle"
    postgresql_url: "https://install.citusdata.com/community/deb.sh"
    user: "shahab"
    postgres_version: "15"
    leader_IP: "172.31.212.90"

  tasks:
  
    - name: Create clsuter
      expect:
        command: /bin/bash -c "cd /home/{{ user }}/csle/metastore && make cluster"
        responses:
          ".*Password.*": "postgres\r"
      register: make_cluster_result

    - debug:
        var: make_cluster_result
